-module(deployment_state).
-behaviour(gen_server).

-export([start_link/0]).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2]).
-export([get_active_env/1, set_active_env/2, get_all_services/0, get_service_status/1]).

-define(STATE_FILE, "/data/deployment_state.json").

-record(state, {
    services = #{} :: map()
}).

start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

init([]) ->
    Services = load_state(),
    io:format("[DEPLOYMENT_STATE] Initialized with services: ~p~n", [maps:keys(Services)]),
    {ok, #state{services = Services}}.

get_active_env(Service) ->
    gen_server:call(?MODULE, {get_active_env, Service}).

set_active_env(Service, Env) ->
    gen_server:call(?MODULE, {set_active_env, Service, Env}).

get_all_services() ->
    gen_server:call(?MODULE, get_all_services).

get_service_status(Service) ->
    gen_server:call(?MODULE, {get_service_status, Service}).

handle_call({get_active_env, Service}, _From, State) ->
    ServiceBin = to_binary(Service),
    ActiveEnv = case maps:get(ServiceBin, State#state.services, undefined) of
        undefined -> <<"blue">>;
        #{<<"active_env">> := Env} -> Env
    end,
    {reply, ActiveEnv, State};

handle_call({set_active_env, Service, Env}, _From, State) ->
    ServiceBin = to_binary(Service),
    EnvBin = to_binary(Env),
    
    OldServiceData = maps:get(ServiceBin, State#state.services, #{}),
    NewServiceData = OldServiceData#{
        <<"active_env">> => EnvBin,
        <<"last_switch">> => iso8601_timestamp(),
        <<"previous_env">> => maps:get(<<"active_env">>, OldServiceData, <<"blue">>)
    },
    
    NewServices = maps:put(ServiceBin, NewServiceData, State#state.services),
    NewState = State#state{services = NewServices},
    
    save_state(NewServices),
    update_nginx_config(NewServices),
    
    io:format("[DEPLOYMENT_STATE] Switched ~s to ~s~n", [ServiceBin, EnvBin]),
    {reply, ok, NewState};

handle_call(get_all_services, _From, State) ->
    {reply, State#state.services, State};

handle_call({get_service_status, Service}, _From, State) ->
    ServiceBin = to_binary(Service),
    Status = maps:get(ServiceBin, State#state.services, #{<<"active_env">> => <<"blue">>}),
    {reply, Status, State};

handle_call(_Request, _From, State) ->
    {reply, {error, unknown_request}, State}.

handle_cast(_Msg, State) ->
    {noreply, State}.

handle_info(_Info, State) ->
    {noreply, State}.

terminate(_Reason, _State) ->
    ok.

load_state() ->
    case file:read_file(?STATE_FILE) of
        {ok, Data} ->
            try jsx:decode(Data, [return_maps]) of
                Map when is_map(Map) -> Map
            catch
                _:_ -> default_services()
            end;
        {error, _} ->
            default_services()
    end.

save_state(Services) ->
    Json = jsx:encode(Services),
    filelib:ensure_dir(?STATE_FILE),
    file:write_file(?STATE_FILE, Json).

default_services() ->
    #{
        <<"orchestrator">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"api-gateway">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"analysis-service">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"harvester-service">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"storage-service">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"chaos-engineering">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()},
        <<"desktop-ui">> => #{<<"active_env">> => <<"blue">>, <<"last_switch">> => iso8601_timestamp()}
    }.

update_nginx_config(Services) ->
    ConfigLines = lists:map(fun({Service, Data}) ->
        ActiveEnv = maps:get(<<"active_env">>, Data, <<"blue">>),
        generate_upstream_config(Service, ActiveEnv)
    end, maps:to_list(Services)),
    
    Config = iolist_to_binary([
        <<"# Auto-generated by Blue-Green Orchestrator\n">>,
        <<"# Generated at: ">>, iso8601_timestamp(), <<"\n\n">>,
        lists:join(<<"\n">>, ConfigLines)
    ]),
    
    file:write_file("/data/nginx_upstream.conf", Config),
    
    reload_nginx().

generate_upstream_config(Service, ActiveEnv) ->
    Port = service_port(Service),
    BlueHost = <<Service/binary, "-blue:", (integer_to_binary(Port))/binary>>,
    GreenHost = <<Service/binary, "-green:", (integer_to_binary(Port))/binary>>,
    
    {ActiveHost, BackupHost} = case ActiveEnv of
        <<"blue">> -> {BlueHost, GreenHost};
        <<"green">> -> {GreenHost, BlueHost}
    end,
    
    iolist_to_binary([
        <<"upstream ">>, Service, <<" {\n">>,
        <<"    server ">>, ActiveHost, <<";\n">>,
        <<"    server ">>, BackupHost, <<" backup;\n">>,
        <<"}\n">>
    ]).

service_port(<<"orchestrator">>) -> 8020;
service_port(<<"api-gateway">>) -> 8000;
service_port(<<"analysis-service">>) -> 8001;
service_port(<<"harvester-service">>) -> 8002;
service_port(<<"storage-service">>) -> 8003;
service_port(<<"chaos-engineering">>) -> 8005;
service_port(<<"desktop-ui">>) -> 3000;
service_port(_) -> 8000.

reload_nginx() ->
    NginxUrl = os:getenv("NGINX_RELOAD_URL", "http://nginx-proxy:8080/reload"),
    case hackney:request(post, list_to_binary(NginxUrl), [], <<>>, []) of
        {ok, 200, _, _} ->
            io:format("[DEPLOYMENT_STATE] Nginx reloaded successfully~n"),
            ok;
        {ok, Status, _, _} ->
            io:format("[DEPLOYMENT_STATE] Nginx reload returned status ~p~n", [Status]),
            {error, Status};
        {error, Reason} ->
            io:format("[DEPLOYMENT_STATE] Failed to reload nginx: ~p~n", [Reason]),
            {error, Reason}
    end.

iso8601_timestamp() ->
    {{Y, M, D}, {H, Mi, S}} = calendar:universal_time(),
    iolist_to_binary(io_lib:format("~4..0B-~2..0B-~2..0BT~2..0B:~2..0B:~2..0BZ", [Y, M, D, H, Mi, S])).

to_binary(Atom) when is_atom(Atom) -> atom_to_binary(Atom, utf8);
to_binary(List) when is_list(List) -> list_to_binary(List);
to_binary(Bin) when is_binary(Bin) -> Bin.
