-module(nginx_config_handler).
-behaviour(cowboy_handler).

-export([init/2]).

init(Req0, State) ->
    Method = cowboy_req:method(Req0),
    handle_request(Method, Req0, State).

handle_request(<<"GET">>, Req0, State) ->
    Config = read_nginx_config(),
    
    Response = #{
        <<"status">> => <<"ok">>,
        <<"config">> => Config,
        <<"timestamp">> => iso8601_timestamp()
    },
    
    Req = cowboy_req:reply(200,
        #{<<"content-type">> => <<"application/json">>},
        jsx:encode(Response),
        Req0),
    {ok, Req, State};

handle_request(<<"POST">>, Req0, State) ->
    Services = deployment_state:get_all_services(),
    generate_and_save_config(Services),
    
    Response = #{
        <<"status">> => <<"ok">>,
        <<"message">> => <<"Nginx configuration regenerated">>,
        <<"timestamp">> => iso8601_timestamp()
    },
    
    Req = cowboy_req:reply(200,
        #{<<"content-type">> => <<"application/json">>},
        jsx:encode(Response),
        Req0),
    {ok, Req, State};

handle_request(_, Req0, State) ->
    Req = cowboy_req:reply(405,
        #{<<"content-type">> => <<"application/json">>},
        jsx:encode(#{<<"error">> => <<"Method not allowed">>}),
        Req0),
    {ok, Req, State}.

read_nginx_config() ->
    case file:read_file("/data/nginx_upstream.conf") of
        {ok, Data} -> Data;
        {error, _} -> <<"# No configuration generated yet">>
    end.

generate_and_save_config(Services) ->
    ConfigLines = lists:map(fun({Service, Data}) ->
        ActiveEnv = maps:get(<<"active_env">>, Data, <<"blue">>),
        generate_upstream_config(Service, ActiveEnv)
    end, maps:to_list(Services)),
    
    Config = iolist_to_binary([
        <<"# Auto-generated by Blue-Green Orchestrator\n">>,
        <<"# Generated at: ">>, iso8601_timestamp(), <<"\n\n">>,
        lists:join(<<"\n">>, ConfigLines)
    ]),
    
    filelib:ensure_dir("/data/nginx_upstream.conf"),
    file:write_file("/data/nginx_upstream.conf", Config).

generate_upstream_config(Service, ActiveEnv) ->
    Port = service_port(Service),
    BlueHost = <<Service/binary, "-blue:", (integer_to_binary(Port))/binary>>,
    GreenHost = <<Service/binary, "-green:", (integer_to_binary(Port))/binary>>,
    
    {ActiveHost, BackupHost} = case ActiveEnv of
        <<"blue">> -> {BlueHost, GreenHost};
        <<"green">> -> {GreenHost, BlueHost}
    end,
    
    iolist_to_binary([
        <<"upstream ">>, Service, <<" {\n">>,
        <<"    server ">>, ActiveHost, <<";\n">>,
        <<"    server ">>, BackupHost, <<" backup;\n">>,
        <<"}\n">>
    ]).

service_port(<<"orchestrator">>) -> 8020;
service_port(<<"api-gateway">>) -> 8000;
service_port(<<"analysis-service">>) -> 8001;
service_port(<<"harvester-service">>) -> 8002;
service_port(<<"storage-service">>) -> 8003;
service_port(<<"chaos-engineering">>) -> 8005;
service_port(<<"desktop-ui">>) -> 3000;
service_port(_) -> 8000.

iso8601_timestamp() ->
    {{Y, M, D}, {H, Mi, S}} = calendar:universal_time(),
    iolist_to_binary(io_lib:format("~4..0B-~2..0B-~2..0BT~2..0B:~2..0B:~2..0BZ", [Y, M, D, H, Mi, S])).
