%%%-------------------------------------------------------------------
%%% @doc Report Generator - Export Analysis Results
%%% 
%%% Generates shareable HTML reports from analysis results.
%%% Supports single analysis, batch analysis, and folder analysis reports.
%%% @end
%%%-------------------------------------------------------------------
-module(report_generator).
%% Helper modules: report_generator_part2

-export([generate_html/1, generate_html/2, generate_summary_html/1]).

-define(REPORT_STYLES, <<"
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
    .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
    .header { background: linear-gradient(135deg, #4361ee, #3730a3); color: white; padding: 40px; border-radius: 12px; margin-bottom: 30px; }
    .header h1 { font-size: 28px; margin-bottom: 10px; }
    .header .meta { opacity: 0.9; font-size: 14px; }
    .card { background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .card h2 { font-size: 18px; margin-bottom: 16px; color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
    .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 20px; }
    .stat { text-align: center; padding: 20px; background: #f8fafc; border-radius: 8px; }
    .stat-value { font-size: 32px; font-weight: bold; color: #4361ee; }
    .stat-label { font-size: 12px; color: #64748b; text-transform: uppercase; margin-top: 4px; }
    .model-list { display: flex; flex-wrap: wrap; gap: 8px; }
    .model-tag { background: #e0e7ff; color: #3730a3; padding: 6px 12px; border-radius: 20px; font-size: 13px; }
    .model-tag.high { background: #dcfce7; color: #166534; }
    .lollapalooza { background: linear-gradient(135deg, #f59e0b, #ef4444); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .lollapalooza h3 { margin-bottom: 8px; }
    .pattern-list { list-style: none; }
    .pattern-list li { padding: 12px 0; border-bottom: 1px solid #e2e8f0; }
    .pattern-list li:last-child { border-bottom: none; }
    .insight { background: #fef3c7; padding: 16px; border-radius: 8px; margin-bottom: 12px; border-left: 4px solid #f59e0b; }
    .file-result { border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
    .file-result h4 { color: #4361ee; margin-bottom: 8px; }
    .footer { text-align: center; color: #64748b; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; }
    @media print { body { background: white; } .container { max-width: 100%; } }
</style>
">>).

generate_html(AnalysisResult) ->
    generate_html(AnalysisResult, #{}).

generate_html(AnalysisResult, Options) ->
    Title = maps:get(title, Options, <<"Mental Models Analysis Report">>),
    Timestamp = format_timestamp(),
    
    Content = case maps:get(<<"results">>, AnalysisResult, undefined) of
        undefined ->
            generate_single_analysis_content(AnalysisResult);
        Results when is_list(Results) ->
            generate_batch_analysis_content(AnalysisResult)
    end,
    
    iolist_to_binary([
        <<"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>">>,
        Title,
        <<"</title>">>,
        ?REPORT_STYLES,
        <<"</head><body><div class='container'>">>,
        <<"<div class='header'><h1>">>, Title, <<"</h1>">>,
        <<"<div class='meta'>Generated: ">>, Timestamp, <<"</div></div>">>,
        Content,
        <<"<div class='footer'>Generated by Ripple Analytics - Mental Models System</div>">>,
        <<"</div></body></html>">>
    ]).

generate_summary_html(Results) when is_list(Results) ->
    generate_html(#{<<"results">> => Results, <<"total_files">> => length(Results)}, 
                  #{title => <<"Batch Analysis Summary">>}).

generate_single_analysis_content(Result) ->
    Models = maps:get(<<"models">>, Result, maps:get(<<"top_models">>, Result, [])),
    AllModels = maps:get(<<"all_models">>, Result, Models),
    Patterns = maps:get(<<"patterns">>, Result, []),
    Insights = maps:get(<<"insights">>, Result, []),
    LollapaloozaDetected = maps:get(<<"lollapalooza_detected">>, Result, false),
    HighScoringCount = maps:get(<<"high_scoring_count">>, Result, 0),
    
    [
        case LollapaloozaDetected of
            true ->
                [<<"<div class='lollapalooza'><h3>LOLLAPALOOZA EFFECT DETECTED</h3>">>,
                 <<"<p>">>, integer_to_binary(HighScoringCount), 
                 <<" mental models converging with high scores - a powerful combination!</p></div>">>];
            false -> <<>>
        end,
        
        <<"<div class='card'><h2>Summary Statistics</h2><div class='stat-grid'>">>,
        stat_box(<<"Models Detected">>, length(AllModels)),
        stat_box(<<"High Scoring">>, HighScoringCount),
        stat_box(<<"Patterns Found">>, length(Patterns)),
        stat_box(<<"Key Insights">>, length(Insights)),
        <<"</div></div>">>,
        
        case Models of
            [] -> <<>>;
            _ ->
                [<<"<div class='card'><h2>Top Mental Models</h2><div class='model-list'>">>,
                 [model_tag(M) || M <- lists:sublist(Models, 10)],
                 <<"</div></div>">>]
        end,
        
        case Patterns of
            [] -> <<>>;
            _ ->
                [<<"<div class='card'><h2>Detected Patterns</h2><ul class='pattern-list'>">>,
                 [[<<"<li>">>, ensure_binary(P), <<"</li>">>] || P <- lists:sublist(Patterns, 10)],
                 <<"</ul></div>">>]
        end,
        
        case Insights of
            [] -> <<>>;
            _ ->
                [<<"<div class='card'><h2>Key Insights</h2>">>,
                 [[<<"<div class='insight'>">>, ensure_binary(I), <<"</div>">>] || I <- lists:sublist(Insights, 5)],
                 <<"</div>">>]
        end
    ].
